// frontend/src/lib/SearchStatus.svelte
<script lang="ts">
  let {
    checked, eligible, resultCount, searching, effectiveConcurrency,
    sourceFailures, error, storageWarning, restartRequired, retryRequired,
    hasMore, batchSize, onrestart, onretry, onmore,
  }: {
    checked: number; eligible: number; resultCount: number; searching: boolean;
    effectiveConcurrency: number; sourceFailures: number; error: string;
    storageWarning: string; restartRequired: boolean; retryRequired: boolean;
    hasMore: boolean; batchSize: number; onrestart: () => void;
    onretry: () => void; onmore: () => void;
  } = $props();

  let moreCount = $derived(Math.min(batchSize, Math.max(0, eligible - checked)));
</script>

<section class="search-status" aria-live="polite">
  {#if eligible > 0}
    <progress value={checked} max={eligible}></progress>
  {/if}
  <div class="status-row">
    <span>
      {#if eligible > 0}{checked} of {eligible} sources checked{:else}{checked} sources checked{/if}
      · {resultCount} book{#if resultCount !== 1}s{/if} found
    </span>
    {#if searching}<span>Concurrency {effectiveConcurrency}</span>{/if}
  </div>
  {#if sourceFailures > 0}<p class="hint">{sourceFailures} source failures</p>{/if}
  {#if error}<p class="error">{error}</p>{/if}
  {#if storageWarning}<p class="error">{storageWarning}</p>{/if}

  {#if !searching}
    <div class="search-actions">
      {#if restartRequired}
        <button type="button" onclick={onrestart}>Restart search</button>
      {:else if retryRequired}
        <button type="button" onclick={onretry}>Retry search batch</button>
      {:else if hasMore}
        <button type="button" onclick={onmore}>Search {moreCount} more</button>
      {/if}
    </div>
  {/if}
</section>

<style>
  .search-status {
    padding: 0.75rem; margin-bottom: 0.75rem;
    background: var(--card-bg); border: 1px solid var(--border); border-radius: 10px;
  }
  progress { display: block; width: 100%; height: 0.5rem; margin-bottom: 0.5rem; accent-color: var(--accent); }
  .status-row { display: flex; justify-content: space-between; gap: 0.75rem; font-size: 0.8rem; color: #666; }
  .search-actions { margin-top: 0.65rem; }
  .search-actions button {
    background: var(--accent); color: white; border: none;
    padding: 0.6rem 1rem; border-radius: 10px; font-size: 0.9rem; cursor: pointer;
  }
  .search-actions button:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
  .hint { font-size: 0.75rem; color: #888; margin-top: 0.35rem; }
  .error { color: #b42318; font-size: 0.8rem; margin-top: 0.4rem; }
  @media (max-width: 420px) {
    .status-row { flex-direction: column; gap: 0.2rem; }
  }
</style>

// frontend/src/features/search/components/SearchStatus.vue
<script lang="ts">
import { defineComponent } from 'vue';
import AppButton from '../../../ui/components/AppButton.vue';

export default defineComponent({
  name: 'SearchStatus', components: { AppButton },
  props: { checked: { type: Number, required: true }, eligible: { type: Number, required: true }, resultCount: { type: Number, required: true }, searching: Boolean, concurrency: { type: Number, required: true }, sourceFailures: { type: Number, required: true }, errorCode: { type: String, required: true }, errorDetail: { type: String, required: true }, storageWarning: Boolean, restartRequired: Boolean, retryRequired: Boolean, hasMore: Boolean, moreCount: { type: Number, required: true } },
  emits: ['restart', 'retry', 'more'],
  computed: { percent(): number { return this.eligible > 0 ? Math.min(100, Math.round((this.checked / this.eligible) * 100)) : 0; } },
});
</script>

<template>
  <section class="status" aria-live="polite">
    <div class="progress" role="progressbar" :aria-valuenow="checked" aria-valuemin="0" :aria-valuemax="eligible || undefined"><span :style="{ transform: `scaleX(${percent / 100})` }" /></div>
    <div class="status-row"><strong>{{ eligible ? $t('search.status.checkedOf', { checked, eligible }) : $t('search.status.checked', { checked }) }}</strong><span>{{ $t('search.status.results', { count: resultCount }) }}</span><span v-if="searching">{{ $t('search.status.concurrency', { count: concurrency }) }}</span></div>
    <p v-if="sourceFailures" class="hint">{{ $t('search.status.failures', { count: sourceFailures }) }}</p>
    <p v-if="errorCode === 'disconnect'" class="error" role="alert">{{ $t('search.status.disconnected') }}</p>
    <p v-else-if="errorCode === 'stale'" class="error" role="alert">{{ $t('search.status.stale') }}<span v-if="errorDetail"> {{ errorDetail }}</span></p>
    <p v-if="storageWarning" class="error" role="alert">{{ $t('search.status.storage') }}</p>
    <div v-if="!searching" class="actions"><AppButton v-if="restartRequired" @click="$emit('restart')">{{ $t('search.actions.restart') }}</AppButton><AppButton v-else-if="retryRequired" @click="$emit('retry')">{{ $t('search.actions.retry') }}</AppButton><AppButton v-else-if="hasMore" @click="$emit('more')">{{ $t('search.actions.more', { count: moreCount }) }}</AppButton></div>
  </section>
</template>

<style scoped>
.status { padding: 1rem; border: 1px solid var(--color-border); border-radius: var(--radius-lg); background: var(--color-paper-raised); }
.progress { height: .45rem; overflow: hidden; border-radius: 999px; background: var(--color-paper-muted); }
.progress span { display: block; width: 100%; height: 100%; transform-origin: left; background: var(--color-accent); transition: transform 160ms ease-out; }
.status-row { display: flex; flex-wrap: wrap; justify-content: space-between; gap: .4rem 1rem; margin-top: .75rem; color: var(--color-ink-muted); font-size: .82rem; }
.status-row strong { color: var(--color-ink); }.hint, .error { margin: .65rem 0 0; font-size: .84rem; }.hint { color: var(--color-warm); }.error { color: var(--color-danger); }.actions { margin-top: .8rem; }
</style>
