// frontend/src/lib/SearchControls.svelte
<script lang="ts">
  import type { SearchIntensity } from './searchPreferences';

  let {
    batchSize = $bindable(),
    intensity = $bindable(),
    advancedConcurrency = $bindable(),
    onchange,
  }: {
    batchSize: number;
    intensity: SearchIntensity;
    advancedConcurrency: number;
    onchange: () => void;
  } = $props();

  function changed() {
    batchSize = Math.min(500, Math.max(1, Math.trunc(batchSize || 1)));
    advancedConcurrency = Math.max(1, Math.trunc(advancedConcurrency || 1));
    onchange();
  }
</script>

<div class="controls" aria-label="Search controls">
  <label>
    <span>Sources per batch</span>
    <input type="number" min="1" max="500" bind:value={batchSize} onchange={changed} />
  </label>
  <label>
    <span>Search intensity</span>
    <select bind:value={intensity} onchange={changed}>
      <option value="gentle">Gentle · 4</option>
      <option value="balanced">Balanced · 8</option>
      <option value="fast">Fast · 16</option>
      <option value="advanced">Advanced</option>
    </select>
  </label>
  {#if intensity === 'advanced'}
    <label>
      <span>Concurrency</span>
      <input type="number" min="1" bind:value={advancedConcurrency} onchange={changed} />
    </label>
  {/if}
</div>

<style>
  .controls {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr));
    gap: 0.5rem;
    margin-bottom: 0.75rem;
  }
  label { display: flex; flex-direction: column; gap: 0.25rem; }
  label span { font-size: 0.72rem; color: #777; font-weight: 600; }
  input, select {
    width: 100%; min-height: 2.25rem; padding: 0.4rem 0.55rem;
    border: 1px solid var(--border); border-radius: 8px;
    background: var(--card-bg); color: var(--fg); font: inherit;
  }
  input:focus, select:focus { outline: 2px solid var(--accent); outline-offset: 1px; }
</style>

// frontend/src/features/search/components/SearchControls.vue
<script lang="ts">
import { defineComponent, type PropType } from 'vue';
import type { SearchIntensity } from '../search-preferences';

export default defineComponent({
  name: 'SearchControls',
  props: {
    batchSize: { type: Number, required: true },
    intensity: { type: String as PropType<SearchIntensity>, required: true },
    advancedConcurrency: { type: Number, required: true },
  },
  emits: ['update:batchSize', 'update:intensity', 'update:advancedConcurrency', 'change'],
  methods: {
    numberValue(event: Event) { return Number((event.target as HTMLInputElement).value); },
    stringValue(event: Event) { return (event.target as HTMLSelectElement).value as SearchIntensity; },
  },
});
</script>

<template>
  <details class="controls">
    <summary>{{ $t('search.controls.title') }}</summary>
    <div class="controls-grid">
      <label><span>{{ $t('search.controls.batchSize') }}</span><input type="number" min="1" max="500" :value="batchSize" @change="$emit('update:batchSize', numberValue($event)); $emit('change')"></label>
      <label><span>{{ $t('search.controls.intensity') }}</span><select :value="intensity" @change="$emit('update:intensity', stringValue($event)); $emit('change')"><option value="gentle">{{ $t('search.controls.gentle') }}</option><option value="balanced">{{ $t('search.controls.balanced') }}</option><option value="fast">{{ $t('search.controls.fast') }}</option><option value="advanced">{{ $t('search.controls.advanced') }}</option></select></label>
      <label v-if="intensity === 'advanced'"><span>{{ $t('search.controls.concurrency') }}</span><input type="number" min="1" :value="advancedConcurrency" @change="$emit('update:advancedConcurrency', numberValue($event)); $emit('change')"></label>
    </div>
  </details>
</template>

<style scoped>
.controls { border: 1px solid var(--color-border); border-radius: var(--radius-md); background: var(--color-paper-raised); }
summary { min-height: 2.75rem; display: flex; align-items: center; padding: .6rem .85rem; color: var(--color-ink-muted); cursor: pointer; font-size: .88rem; font-weight: 700; }
.controls-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr)); gap: .75rem; padding: 0 .85rem .85rem; }
label { display: grid; gap: .35rem; } label span { color: var(--color-ink-muted); font-size: .78rem; font-weight: 700; }
input, select { min-height: 2.75rem; width: 100%; border: 1px solid var(--color-border); border-radius: var(--radius-sm); padding: .55rem .7rem; background: white; color: var(--color-ink); }
</style>
